export const state = {
    activeCollection: null,
    page: 1,
    limit: 20,
    isSearch: false,
    editId: null,
    debounce: null,
    boostRows: [],
    knownFields: [],
    openMenuEl: null,
    importJobs: [],
    importEventSource: null,
    importStreamCollection: null,
    importPanelDismissed: false,
    docsAbortController: null,
    searchAbortController: null,
    statsAbortController: null,
};

const $ = id => document.getElementById(id);

export const dom = {
    collectionList:       $('collectionList'),
    bcCollection:         $('bcCollection'),
    statTotalDocs:        $('statTotalDocs'),
    statTotalTokens:      $('statTotalTokens'),
    docList:              $('docList'),
    docRange:             $('docRange'),
    prevPage:             $('prevPage'),
    nextPage:             $('nextPage'),
    pageLabel:            $('pageLabel'),
    perPageSelect:        $('perPageSelect'),
    searchInput:          $('searchInput'),
    boostToggleBtn:       $('boostToggleBtn'),
    boostDrawer:          $('boostDrawer'),
    boostBadge:           $('boostBadge'),
    boostRowsCont:        $('boostRows'),
    addBoostRowBtn:       $('addBoostRowBtn'),
    fieldSuggestions:     $('fieldSuggestions'),
    sidebar:              $('sidebar'),
    sidebarOverlay:       $('sidebarOverlay'),
    menuBtn:              $('menuBtn'),
    sidebarCloseBtn:      $('sidebarCloseBtn'),
    addModal:             $('addModal'),
    addModalCollection:   $('addModalCollection'),
    addDocIdLabel:        $('addDocIdLabel'),
    addDocText:           $('addDocText'),
    indexDocBtn:          $('indexDocBtn'),
    bulkModal:            $('bulkModal'),
    bulkModalCollection:  $('bulkModalCollection'),
    bulkFileInput:        $('bulkFileInput'),
    bulkCharCount:        $('bulkCharCount'),
    bulkValidation:       $('bulkValidation'),
    bulkDocText:          $('bulkDocText'),
    submitBulkBtn:        $('submitBulkBtn'),
    importPanel:          $('importPanel'),
    importPanelSummary:   $('importPanelSummary'),
    dismissImportPanelBtn:$('dismissImportPanelBtn'),
    importList:           $('importList'),
    editModal:            $('editModal'),
    editDocIdLabel:       $('editDocIdLabel'),
    editDocText:          $('editDocText'),
    saveEditBtn:          $('saveEditBtn'),
    newCollectionModal:   $('newCollectionModal'),
    newCollectionName:    $('newCollectionName'),
    createCollectionBtn:  $('createCollectionBtn'),
    toast:                $('toast'),
};
